services:
  - type: web
    name: github-uploader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GITHUB_TOKEN
        fromService: your-github-token-service-name